[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
convert_case = "0.6.0"
flate2 = "1.0.35"
itertools.workspace = true
pretty_assertions.workspace = true
proc-macro2.workspace = true
quote.workspace = true
schemars = { workspace = true, features = ["chrono04"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time = { version = "0.3.36", default-features = false }
tombi-config = { workspace = true, features = ["jsonschema"] }
ungrammar = "1.16.1"
xshell = "0.2.7"
zip = { version = "2.2.1", default-features = false, features = [
  "deflate",
  "time",
] }
