[package]
name = "tombi-future"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true

[features]
default = ["native"]
native = []
wasm = []
